server:
  port: 8084

spring:
  application:
    name: log-processor
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-processors
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

opensearch:
  host: localhost
  port: 9200

logging:
  level:
    com.logmonitoring: DEBUG
    org.apache.kafka: INFO